// Mock Email Pack v1 — 12 cases med klassificering
export const emails = [
  {
    id: 'case-01',
    from: 'kund@byggbolag.se',
    subject: 'Förfrågan – totalentreprenad lagerhall',
    body: 'Hej,\nVi ska bygga en lagerhall på ca 1200 kvm och vill ha offert.\nBehöver start inom 2–3 månader.\nKan ni återkomma med ungefärlig prisbild och nästa steg?\n\n/Andreas',
    priority: 'high',
    tag: 'NY LEAD',
    tagColor: 'emerald',
    jonas: true,
    assignee: 'Jonas',
    nextStep: 'Bedöm lead-kvalitet, kontrollera kapacitet, boka avstämning eller delegera till projektledare för initial kalkyl.',
    draft: 'Hej Andreas,\nTack för din förfrågan. Vi tar gärna en titt på detta. Kan vi boka ett kort samtal för att gå igenom förutsättningarna?\n\nMvh Jonas',
    batchTag: null,
    approval: true,
    category: 'lead'
  },
  {
    id: 'case-02',
    from: 'privatperson@gmail.com',
    subject: 'Bygga om lite',
    body: 'Tjena,\nBehöver hjälp med lite bygggrejer, vet inte riktigt vad det kostar.\nKan ni höra av er?',
    priority: 'low',
    tag: 'OKLAR LEAD',
    tagColor: 'gray',
    jonas: false,
    assignee: 'Projektledare',
    nextStep: 'Standardsvar: be om mer detaljer eller hänvisa vidare. Ingen VD-tid.',
    draft: 'Hej,\nTack för att du hör av dig. Kan du beskriva lite mer vad du tänker dig? Omfattning, tidsram och budget hjälper oss bedöma om vi kan hjälpa till.\n\nMvh',
    batchTag: null,
    approval: false,
    category: 'lead'
  },
  {
    id: 'case-03',
    from: 'projektledare@bolaget.se',
    subject: 'Problem med leverans – risk för försening',
    body: 'Hej,\nLeverantören av stålbalkar är sena med minst 1 vecka.\nDet påverkar tidsplanen direkt.\nHur vill du att vi hanterar detta mot kund?',
    priority: 'high',
    tag: 'TIDSRISK',
    tagColor: 'red',
    jonas: true,
    assignee: 'Jonas',
    nextStep: 'Bedöm kundpåverkan, besluta om proaktiv kommunikation eller avvakta. Kräver VD-beslut pga kundrelation.',
    draft: null,
    batchTag: null,
    approval: true,
    category: 'project'
  },
  {
    id: 'case-04',
    from: 'projektledare@bolaget.se',
    subject: 'Status vecka 12',
    body: 'Hej,\nAllt rullar på enligt plan.\nInga avvikelser just nu.',
    priority: 'low',
    tag: 'STATUS',
    tagColor: 'blue',
    jonas: false,
    assignee: 'Projektledare',
    nextStep: 'Notera. Ingen åtgärd krävs. Arkivera till statusöversikt.',
    draft: null,
    batchTag: null,
    approval: false,
    category: 'project'
  },
  {
    id: 'case-05',
    from: 'leverantor@material.se',
    subject: 'Justering av priser Q2',
    body: 'Hej,\nVi behöver justera priserna med ca 8% från nästa månad pga ökade inköpskostnader.\nÅterkom om ni vill diskutera.',
    priority: 'medium',
    tag: 'PRIS',
    tagColor: 'amber',
    jonas: true,
    assignee: 'Jonas',
    nextStep: 'Bedöm påverkan på marginaler i pågående projekt. Boka förhandlingssamtal eller godkänn.',
    draft: 'Hej,\nTack för informationen. Vi vill gärna diskutera detta. Kan vi ta ett kort samtal?\n\nMvh Jonas',
    batchTag: null,
    approval: true,
    category: 'supplier'
  },
  {
    id: 'case-06',
    from: 'leverantor@transport.se',
    subject: 'Leveranstid tisdag',
    body: 'Hej,\nFunkar det att vi kommer kl 07:00 istället för 08:00?',
    priority: 'low',
    tag: 'LOGISTIK',
    tagColor: 'blue',
    jonas: false,
    assignee: 'Projektledare',
    nextStep: 'Delegera till projektledaren som äger tidsplaneringen på plats.',
    draft: null,
    batchTag: 'småfrågor',
    approval: false,
    category: 'supplier'
  },
  {
    id: 'case-07',
    from: 'snickare@bolaget.se',
    subject: 'Val av material kund X',
    body: 'Hej,\nSka vi köra standardlösningen eller uppgradera materialet här?',
    priority: 'low',
    tag: 'INTERN',
    tagColor: 'purple',
    jonas: false,
    assignee: 'Projektledare',
    nextStep: 'Delegera. Projektledaren har mandat att besluta materialval inom budget.',
    draft: null,
    batchTag: null,
    approval: false,
    category: 'internal'
  },
  {
    id: 'case-08',
    from: 'projektledare@bolaget.se',
    subject: 'Kund vill ändra omfattning',
    body: 'Hej,\nKunden vill lägga till extra arbete som påverkar pris och tid.\nHur vill du att vi tar detta?',
    priority: 'medium',
    tag: 'SCOPE',
    tagColor: 'amber',
    jonas: true,
    assignee: 'Jonas',
    nextStep: 'Bedöm tilläggets storlek. Om det påverkar pris >10% eller tid >1 vecka: Jonas beslutar. Annars: projektledare.',
    draft: null,
    batchTag: null,
    approval: true,
    category: 'project'
  },
  {
    id: 'case-09',
    from: 'kund@projekt.se',
    subject: 'Inte nöjd med utförandet',
    body: 'Hej,\nVi är inte nöjda med hur arbetet ser ut just nu.\nVill att ni återkommer omgående.',
    priority: 'high',
    tag: 'MISSNÖJE',
    tagColor: 'red',
    jonas: true,
    assignee: 'Jonas',
    nextStep: 'Omedelbar kundkontakt från Jonas. Eskalering med hög kundrelationsrisk. Ring idag.',
    draft: null,
    batchTag: null,
    approval: true,
    category: 'customer'
  },
  {
    id: 'case-10',
    from: 'arkitekt@projekt.se',
    subject: 'Reviderade ritningar',
    body: 'Hej,\nSe bifogade ritningar.\nBehöver återkoppling om detta påverkar er del.',
    priority: 'medium',
    tag: 'RITNING',
    tagColor: 'cyan',
    jonas: false,
    assignee: 'Projektledare',
    nextStep: 'Vidarebefordra till projektledare för teknisk bedömning. Jonas behöver bara in om det påverkar budget/tid väsentligt.',
    draft: null,
    batchTag: null,
    approval: false,
    category: 'project'
  },
  {
    id: 'case-11',
    from: 'kund1@projekt.se',
    subject: 'Snabb fråga – vilken dag',
    body: 'Hej,\nVilken dag kommer ni nästa gång?',
    priority: 'low',
    tag: 'SMÅFRÅGA',
    tagColor: 'gray',
    jonas: false,
    assignee: 'Projektledare',
    nextStep: 'Batch med liknande småfrågor. Delegera.',
    draft: null,
    batchTag: 'småfrågor',
    approval: false,
    category: 'batch'
  },
  {
    id: 'case-12',
    from: 'kund2@projekt.se',
    subject: 'Snabb fråga – flytta möte',
    body: 'Hej,\nKan ni flytta mötet från torsdag till fredag?',
    priority: 'low',
    tag: 'SMÅFRÅGA',
    tagColor: 'gray',
    jonas: false,
    assignee: 'Projektledare',
    nextStep: 'Batch med liknande småfrågor. Delegera.',
    draft: null,
    batchTag: 'småfrågor',
    approval: false,
    category: 'batch'
  }
];
